<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="myrobot">

	<xacro:property name="multiplier" value="${1}"/>
	<xacro:property name="reduc_9_actuator_diameter" value="${0.077 * multiplier}"/>
	<xacro:property name="reduc_9_actuator_height" value="${0.058 * multiplier}"/>
	<xacro:property name="waist_arm_height" value="${0.01 * multiplier}"/>

	<xacro:property name="shoulder_arm_angle_offset" value="${-0.5*pi - 0.52/4.5*pi}"/>
	<xacro:property name="shoulder_arm_length" value="${0.1385 * multiplier}"/>
	<xacro:property name="shoulder_arm_width" value="${0.047 * multiplier}"/>

	<xacro:property name="arm_height" value="${0.03 * multiplier}"/>

	<xacro:property name="elbow_arm1_angle_offset" value="${-pi/6 + 0.15/2.5*pi}"/>
	<xacro:property name="elbow_arm2_angle_offset" value="-${pi/4}"/>
	<xacro:property name="elbow_arm1_length" value="${0.065 * multiplier}"/>
	<xacro:property name="elbow_arm2_length" value="${0.110 * multiplier}"/>
	<xacro:property name="elbow_arm_width" value="${0.020 * multiplier}"/>
	
	<xacro:property name="wrist_angle_offset" value="${-pi/4 - elbow_arm1_angle_offset}"/>
	<xacro:property name="wrist_diameter" value="${0.04 * multiplier}"/>

	<xacro:property name="end_effector_height" value="${0.04 * multiplier}"/>

	
	<material name="black">
		<color rgba="0 0 0 1"/>
	</material>
	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>
	<material name="orange">
		<color rgba="1 0.6 0 1"/>
	</material>
	<material name="red">
		<color rgba="1 0 0 1"/>
	</material>
	<material name="green">
		<color rgba="0 1 0 1"/>
	</material>
	<material name="blue">
		<color rgba="0 0 1 1"/>
	</material>
	<material name="thing">
		<color rgba="0.2 0.7 0.4 1"/>
	</material>
	
	<link name="world" />

	<!-- LINKS -->
	
	<link name="waist">
		<visual>
			<geometry>
				<cylinder length="${reduc_9_actuator_height}" radius="${reduc_9_actuator_diameter/2}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 -${reduc_9_actuator_height/2}"/>
			<material name="orange"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${reduc_9_actuator_height}" radius="${reduc_9_actuator_diameter/2}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 -${reduc_9_actuator_height/2}"/>
		</collision>
	</link>
	

	<link name="waist_arm">
		<visual>
			<geometry>
				<cylinder radius="${reduc_9_actuator_diameter/2}" length="${waist_arm_height}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${waist_arm_height/2}"/>
			<material name="black"/>
		</visual>
		<collision>
			<geometry>
				<box size="${reduc_9_actuator_diameter} ${reduc_9_actuator_diameter} ${waist_arm_height}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${waist_arm_height/2}"/>
		</collision>
	</link>

	<link name="shoulder">
		<visual>
			<geometry>
				<cylinder length="${reduc_9_actuator_height}" radius="${reduc_9_actuator_diameter/2}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 -${reduc_9_actuator_height/2}"/>
			<material name="blue"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${reduc_9_actuator_height}" radius="${reduc_9_actuator_diameter/2}" />
			</geometry>                                                                                                  
			<origin rpy="0 0 0" xyz="0 0 -${reduc_9_actuator_height/2}"/>
		</collision>
	</link> 

	<link name="shoulder_arm">
		<visual>
			<geometry>
				<box size="${shoulder_arm_length} ${shoulder_arm_width} ${arm_height}" />
			</geometry>
			<origin rpy="0 0 0" xyz="${shoulder_arm_length/2} 0 ${arm_height/2}"/>
			<material name="blue"/>
		</visual>
		<collision>
			<geometry>
				<box size="${shoulder_arm_length} ${reduc_9_actuator_diameter} 0.03" />
			</geometry>
			<origin rpy="0 0 0" xyz="${shoulder_arm_length/2} 0 ${arm_height/2}"/>
		</collision>
	</link>
	
	<link name="elbow">
		<visual>
			<geometry>
				<cylinder length="${reduc_9_actuator_height}" radius="${reduc_9_actuator_diameter/2}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${-reduc_9_actuator_height/2}"/>
			<material name="white"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${reduc_9_actuator_height}" radius="${reduc_9_actuator_diameter/2}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 -${reduc_9_actuator_height/2}"/>
			<material name="white"/>
		</collision>
	</link>

	<link name="elbow_arm1">
		<visual>
			<geometry>
				<box size="${elbow_arm1_length} ${elbow_arm_width} ${arm_height}" />
			</geometry>
			<origin rpy="0 0 0" xyz="${elbow_arm1_length/2} 0 0"/>
			<material name="red"/>
		</visual>
		<collision>
			<geometry>
				<box size="${elbow_arm1_length} ${reduc_9_actuator_diameter} ${arm_height}" />
			</geometry>
			<origin rpy="0 0 0" xyz="${elbow_arm1_length/2} 0 ${arm_height/2}"/>
		</collision>
	</link>

	<link name="elbow_arm2">
		<visual>
			<geometry>
				<box size="${elbow_arm2_length} ${elbow_arm_width} ${arm_height}" />
			</geometry>
			<origin rpy="0 0 0" xyz="${elbow_arm2_length/2} 0 0"/>
			<material name="red"/>
		</visual>
		<collision>
			<geometry>
				<box size="${elbow_arm2_length} ${reduc_9_actuator_diameter} ${arm_height}" />
			</geometry>
			<origin rpy="0 0 0" xyz="${elbow_arm2_length/2} 0 ${arm_height/2}"/>
		</collision>
	</link>

	<link name="wrist">
		<visual>
			<geometry>
				<cylinder length="${reduc_9_actuator_height/2}" radius="${wrist_diameter/2}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<material name="green"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${reduc_9_actuator_height/2}" radius="${wrist_diameter/2}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision>
	</link>

	<link name="end_effector">
		<visual>
			<geometry>
				<cylinder length="${end_effector_height}" radius="${wrist_diameter/4}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${end_effector_height/2}"/>
			<material name="thing"/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${reduc_9_actuator_height/2}" radius="${wrist_diameter/2}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision>
	</link>

	<!-- MODELING JOINTS -->
	
	<joint name="waist_arm_join" type="fixed">
		<origin xyz="0 0 0" 
				rpy="0 0 0"/>
		<parent link="waist"/>
		<child link="waist_arm"/>
	</joint>
	
	<joint name="shoulder_arm_join" type="fixed">
		<origin xyz="0 0 0" 
				rpy="0 0 ${shoulder_arm_angle_offset}"/>
		<parent link="shoulder"/>
		<child link="shoulder_arm"/>
	</joint>
	
	<joint name="elbow_arm_join" type="fixed">
		<origin xyz="0 0 ${arm_height/2}" 
				rpy="0 0 ${elbow_arm1_angle_offset}"/>
		<parent link="elbow"/>
		<child link="elbow_arm1"/>
	</joint>
	
	<joint name="elbow_arm2_join" type="fixed">
		<origin xyz="${elbow_arm1_length} 0 0" 
				rpy="0 0 ${elbow_arm2_angle_offset}"/>
		<parent link="elbow_arm1"/>
		<child link="elbow_arm2"/>
	</joint>
	
	<joint name="end_effector_join" type="fixed">
		<origin xyz="${wrist_diameter/2} 0 0" 
				rpy="0 ${pi/2} 0"/>
		<parent link="wrist"/>
		<child link="end_effector"/>
        <limit effort="30" velocity="1.0" lower="0" upper="${3.547/2.5 * pi}" />
	</joint>

	<!-- MOVING JOINTS -->
	
	<joint name="waist_joint" type="revolute">
		<origin xyz="0 0 ${reduc_9_actuator_height}"/>
		<axis rpy="0 0 0" xyz="0 0 1"/>
		<parent link="world"/>
		<child link="waist"/>
        <limit effort="30" velocity="1.0" lower="-${pi}" upper="${pi}" />
	</joint>

	<joint name="shoulder_joint" type="revolute">
		<origin xyz="0 0 ${waist_arm_height + reduc_9_actuator_diameter/2}"
				rpy="-${pi/2} 0 0"/>
		<axis rpy="0 0 0" xyz="0 0 1"/>
		<parent link="waist"/>
		<child link="shoulder"/>
        <limit effort="30" velocity="1.0" lower="-${1.7}" upper="${2.42}" />
	</joint>
	
	
	<joint name="elbow_joint" type="revolute">
		<origin xyz="${cos(shoulder_arm_angle_offset) * shoulder_arm_length} ${sin(shoulder_arm_angle_offset) * shoulder_arm_length} 0" 
				rpy="${pi} 0 0"/>
		<axis rpy="0 0 0" xyz="0 0 1"/>
		<parent link="shoulder"/>
		<child link="elbow"/>
        <limit effort="30" velocity="1.0" lower="0" upper="${2.28}" />
	</joint>
	
	<joint name="wrist_joint" type="revolute">
		<origin xyz="${elbow_arm2_length} 0 -${arm_height/2}" 
				rpy="0 0 ${wrist_angle_offset}"/>
		<axis rpy="0 0 0" xyz="0 0 1"/>
		<parent link="elbow_arm2"/>
		<child link="wrist"/>
        <limit effort="30" velocity="1.0" lower="${-pi/2}" upper="${pi}" />
	</joint>

</robot>